version: '2'
services:
    mysql:
      image: mysql:5.7
      restart: always
      volumes:
        - "./mysql/dataBase:/var/lib/mysql"
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: digital_lab
        MYSQL_ROOT_PASSWORD: ThePassword
        MYSQL_USER: springuser
        MYSQL_PASSWORD: ThePassword

    webapp:
      image: digital-lab:0.0.1-SNAPSHOT
      environment:
        MYSQL_HOST: mysql
        MYSQL_PORT: 3306
      ports:
        - "8080:8080"
      depends_on:
        - mysql
