version: '2'
services:
    mysql:
      image: mysql:5.7
      restart: always
      volumes:
        - "./mysql/dataBase:/var/lib/mysql"
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: db_example
        MYSQL_ROOT_PASSWORD: ThePassword
        MYSQL_USER: springuser
        MYSQL_PASSWORD: ThePassword